title: "FiddleBops - 创意音乐创作游戏"
description: "FiddleBops 是一个创新的音乐创作游戏，让每个人都能轻松创作出独特的音乐作品。无需音乐基础，即刻开始你的音乐创作之旅！"
favicon: "/favicon.svg"

# Open Graph 配置
og:
  type: "website"
  site_name: "FiddleBops"
  image: "/og-image.jpg"
  image_alt: "FiddleBops 游戏界面预览"
  locale: "zh_CN"

# Twitter Card 配置
twitter:
  card: "summary_large_image"
  creator: "@FiddleBops" 